name: "QMK Firmware Build NEW"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test:
    name: Action Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Firmware
        uses: ./
        with:
          keymap-path: "keyboards/crkbd/rev1/keymaps/eruditorium"
          keyboard: "crkbd/rev1"
          keymap: "eruditorium"
      - name: Upload a Firmware
        uses: actions/upload-artifact@v3.1.2
        with:
          name: firmware
          path: build
