name: QMK userspace Build NEW
on:
  workflow_dispatch:
  push:
    paths:
      - "keyboards/**"
      - "keymaps/*"
      - ".github/workflows/*"
      - "*.def"
      - "*.c"
      - "*.h"

steps:
  - uses: actions/checkout@v1

  - name: Build Firmware
    uses: ./
    with:
      keymap-path: "keyboards/crkbd/rev1/keymaps/eruditorium"
      keyboard: "crkbd/rev1"
      keymap: "eruditorium"

  - name: Upload a Firmware
    uses: actions/upload-artifact@v3.1.2
    with:
      name: firmware
      path: build
